//! Extension trait for downstream crates to modify WGSL IR after transpilation
//! but before rendering/instantiation.
//!
//! Extensions are specified via the `extensions` attribute on the `#[wgsl]`
//! macro:
//!
//! ```ignore
//! #[wgsl(crate_path = crate, extensions = [my_crate::MyExt])]
//! pub mod my_shader { ... }
//! ```
//!
//! Each extension type must implement [`WgslExtension`]. The
//! [`modify_ir`](WgslExtension::modify_ir) method is called on the
//! base/template IR module **before** type instantiation, so modifications made
//! by extensions are carried through every `instantiate()` call.

/// A trait for modifying WGSL IR modules after transpilation.
///
/// Extensions can inspect IR items (including their preserved Rust attributes)
/// and add, remove, or modify items. The IR module is passed mutably, so
/// extensions can make any changes they need.
///
/// # Example
///
/// ```ignore
/// use wgsl_rs::ir;
/// use wgsl_rs::WgslExtension;
///
/// pub struct SlabItemExt;
///
/// impl WgslExtension for SlabItemExt {
///     fn modify_ir(module: &mut ir::Module) {
///         // Find structs with #[derive(SlabItem)] in their attrs
///         let slab_structs: Vec<(String, Vec<ir::Field>)> = module.items.iter()
///             .filter_map(|item| match item {
///                 ir::Item::Struct(s) if has_derive(&s.attrs, "SlabItem") => {
///                     Some((s.name.clone(), s.fields.clone()))
///                 }
///                 _ => None,
///             })
///             .collect();
///
///         // Add helper functions for each slab struct
///         for (name, fields) in slab_structs {
///             module.items.push(ir::Item::Fn(make_slab_read_fn(&name, &fields)));
///             module.items.push(ir::Item::Fn(make_slab_write_fn(&name, &fields)));
///         }
///     }
/// }
/// ```
pub trait WgslExtension {
    /// Modify the IR module in place.
    ///
    /// This method is called in the IR constructor generated by the `#[wgsl]`
    /// macro, after the module's IR items have been constructed but before
    /// type instantiation (for template modules).
    fn modify_ir(module: &mut crate::ir::Module);
}
